package com.carrey.HibernateTest.pojo;

// default package
// Generated 2016-2-19 23:27:16 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int sid;
	private String name;
	private String gender;
	private Date birth;
	private String phone;
	private String postcode;
	private Address address;

	public Student() {
	}

	public Student(int sid) {
		this.sid = sid;
	}



	public Student(int sid, String name, String gender, Date birth, Address address) {
		super();
		this.sid = sid;
		this.name = name;
		this.gender = gender;
		this.birth = birth;
		this.address = address;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

}
